# Generated by Django 5.1.4 on 2025-01-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_book_creadted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avaliable',
            new_name='available',
        ),
    ]
