# Generated by Django 5.1.4 on 2025-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_rating_alter_book_author_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
